[package]
name = "config"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
once_cell.workspace = true
